INSERT INTO plot_dtls (REGISTERED_OWNER , CITY , DISTRICT , STATE ,AREA_HA ,UNIT_PRICE,CREATE_TIME,UPDATE_TIME ) VALUES
  ('MRC', 'chd', 'chd','chd',1500,300000,CURRENT_TIME,CURRENT_TIME),
  ('Shobha', 'chd', 'chd','chd',2500,300000,CURRENT_TIME,CURRENT_TIME),
  ('JP', 'New Delhi', 'New Delhi','New Delhi',4500,500000,CURRENT_TIME,CURRENT_TIME);
